services:
  - type: web
    name: kardes-magaza
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
